apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: k8s.gcr.io/echoserver:1.4
      ports:
        - containerPort: 3000
